# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0f3ad700239588aaa90e97fef4c3a286fa595a162391b044ef0a4c743562f0720b4bbe96990da580e576a3fdecba5a62ac6889d5558585df7f358ea1b211e9c

test:
  secret_key_base: 220663f06f5b09a171ccb5ec5da5b2fb5fa42337cced0bc567457d0bccc832cae4749795f57cbe2e66505709d0041ae2716ab93ba1fde54677c9d94e90a2b6f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
