# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ps3 = Console.create(name: 'PS3', description: 'Sony PlayStation 3')
ps4 = Console.create(name: 'PS4', description: 'Sony PlayStation 4')

Game.create(name: 'EA Skate', console: ps3, releasedate: '2006-05-01', owned: true, completed: true, digital: false)
Game.create(name: 'EA Skate 2', console: ps3, releasedate: '2006-05-01', owned: true, completed: true, digital: false)
Game.create(name: 'EA Skate 3', console: ps3, releasedate: '2006-05-01', owned: true, completed: true, digital: false)
Game.create(name: 'Darksiders', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Metal Gear Solid 4', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Call of Duty: Black Ops', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Call of Duty: MW3 ', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Uncharted', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Uncharted 2', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Uncharted 3', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'GTA IV', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'GTA IV: Liberty city stories', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'Red Dead Redemption', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'Little Big Planet', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Little Big Planet 2', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'X-Men: Volverine', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Batman: Arkham Assylum', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'Resident Evil 5', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Silent Hill: Homecomming', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Guitar Hero 3', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Guitar Hero: Aerosmith', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Buzz Quiz TV', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Mafia 2', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Heavy Rain', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Final Fantasy XIII', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'Killzone 2', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Tony Hawks Proving Ground', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'Shaun White Snowboarding', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Time Crisis 4', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Devil May Cry 4', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'Mirror\'s Edge', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'inFamous', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Dante\'s Inferno', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: true)
Game.create(name: 'Bayonetta', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Max Payne 3', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Rayman Origins', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Metal Gear Rising: Revengeance', console: ps3, releasedate: '2013-02-21', owned: true, completed: false, digital: false)
Game.create(name: 'THPS:HD', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: true)
Game.create(name: 'Call of Duty: Black Ops 2', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: false)
Game.create(name: 'Darksiders II', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'Just Cause 2', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: false)
Game.create(name: 'DMC - Devil may cry', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Metro: Last Light', console: ps3, releasedate: '2013-03-14', owned: true, completed: true, digital: true)
Game.create(name: 'The Last of Us', console: ps3, releasedate: '2013-06-14', owned: true, completed: true, digital: false)
Game.create(name: 'Mirror\'s Edge Catalyst', console: ps4, releasedate: '2016-06-09', owned: true, completed: false, digital: false)
Game.create(name: 'Beyond - Two Souls', console: ps3, releasedate: '2013-10-09', owned: true, completed: true, digital: false)
Game.create(name: 'GTA V', console: ps3, releasedate: '2013-09-23', owned: true, completed: true, digital: false)
Game.create(name: 'Dead Nation', console: ps3, releasedate: '2012-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Joe Danger', console: ps3, releasedate: '2012-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Watch Dogs', console: ps4, releasedate: '2014-04-01', owned: true, completed: true, digital: false)
Game.create(name: 'Assassins Creed IV (4) - Black Flag', console: ps4, releasedate: '2013-11-29', owned: true, completed: false, digital: false)
Game.create(name: 'Call of Duty - Ghosts', console: ps4, releasedate: '2013-11-29', owned: true, completed: true, digital: false)
Game.create(name: 'Metal Gear Solid V - The Phantom Pain ', console: ps4, releasedate: '2015-09-01', owned: true, completed: false, digital: false)
Game.create(name: 'Tomb Raider', console: ps4, releasedate: '2014-01-31', owned: true, completed: true, digital: false)
Game.create(name: 'Little Big Planet: Karting', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Re:Member', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Bioshock: Infinite', console: ps3, releasedate: '2000-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Don\'t starve', console: ps3, releasedate: '2000-01-01', owned: true, completed: true, digital: true)
Game.create(name: 'Resogun', console: ps4, releasedate: '2014-01-01', owned: true, completed: true, digital: true)
Game.create(name: 'Contrast', console: ps4, releasedate: '2014-01-01', owned: true, completed: true, digital: true)
Game.create(name: 'Warframe', console: ps4, releasedate: '2014-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Outlast', console: ps4, releasedate: '2014-02-05', owned: true, completed: true, digital: true)
Game.create(name: 'Dead Nation', console: ps4, releasedate: '2015-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Dark Souls II', console: ps3, releasedate: '2014-03-14', owned: true, completed: false, digital: false)
Game.create(name: 'Metal Gear Solid - Ground Zeroes', console: ps4, releasedate: '2014-03-21', owned: true, completed: true, digital: false)
Game.create(name: 'The Golf Club', console: ps4, releasedate: '2014-05-31', owned: true, completed: true, digital: true)
Game.create(name: 'Trials Fusion', console: ps4, releasedate: '2014-02-01', owned: true, completed: true, digital: true)
Game.create(name: 'The Last of Us Remastered', console: ps4, releasedate: '2014-07-30', owned: true, completed: true, digital: false)
Game.create(name: 'Driveclub', console: ps4, releasedate: '2014-10-08', owned: true, completed: true, digital: true)
Game.create(name: 'Dead Island 2', console: ps4, releasedate: '2018-03-01', owned: false, completed: false, digital: false)
Game.create(name: 'Rise of the Tomb Raider', console: ps4, releasedate: '2016-10-11', owned: true, completed: true, digital: false)
Game.create(name: 'Fez', console: ps4, releasedate: '2014-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Strider', console: ps4, releasedate: '2014-06-01', owned: true, completed: false, digital: true)
Game.create(name: 'Crysis 3', console: ps3, releasedate: '2012-06-30', owned: true, completed: false, digital: true)
Game.create(name: 'Dead Space 3', console: ps3, releasedate: '2013-06-30', owned: true, completed: false, digital: true)
Game.create(name: 'Doki-Doki Universe', console: ps4, releasedate: '2014-04-01', owned: true, completed: false, digital: true)
Game.create(name: 'Trine 2', console: ps4, releasedate: '2014-06-01', owned: true, completed: false, digital: true)
Game.create(name: 'PixelJunk', console: ps4, releasedate: '2014-06-01', owned: true, completed: false, digital: true)
Game.create(name: 'Payday 2', console: ps3, releasedate: '2013-08-30', owned: true, completed: false, digital: true)
Game.create(name: 'Sly Cooper: Thieves in Time', console: ps4, releasedate: '2014-05-01', owned: true, completed: false, digital: true)
Game.create(name: 'Stick it to the man', console: ps4, releasedate: '2014-04-01', owned: true, completed: false, digital: true)
Game.create(name: 'Brothers: a Tale of Two Sons', console: ps3, releasedate: '2013-09-01', owned: true, completed: false, digital: true)
Game.create(name: 'Metro 2033 Redux', console: ps4, releasedate: '2014-08-29', owned: true, completed: true, digital: false)
Game.create(name: 'Metro Last Light Redux', console: ps4, releasedate: '2014-08-29', owned: true, completed: true, digital: true)
Game.create(name: 'Velocity 2X', console: ps4, releasedate: '2014-09-01', owned: true, completed: true, digital: true)
Game.create(name: 'Until Dawn', console: ps4, releasedate: '2015-08-26', owned: true, completed: true, digital: false)
Game.create(name: 'Dust: An Elysian Tail', console: ps4, releasedate: '2014-09-01', owned: true, completed: false, digital: true)
Game.create(name: 'The Evil Within', console: ps4, releasedate: '2014-10-12', owned: true, completed: true, digital: false)
Game.create(name: 'Nidhogg', console: ps4, releasedate: '2014-11-15', owned: true, completed: true, digital: true)
Game.create(name: 'inFamous: First light', console: ps4, releasedate: '2015-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'The Swapper', console: ps4, releasedate: '2014-05-01', owned: true, completed: false, digital: true)
Game.create(name: 'Dying Light', console: ps4, releasedate: '2015-01-30', owned: true, completed: false, digital: false)
Game.create(name: 'The Order: 1886', console: ps4, releasedate: '2015-02-20', owned: false, completed: false, digital: false)
Game.create(name: 'Bloodborne', console: ps4, releasedate: '2015-03-25', owned: false, completed: false, digital: false)
Game.create(name: 'Witcher 3: Wild Hunt', console: ps4, releasedate: '2015-05-19', owned: false, completed: false, digital: false)
Game.create(name: 'Uncharted 4', console: ps4, releasedate: '2016-04-27', owned: true, completed: true, digital: false)
Game.create(name: 'Just Cause 3', console: ps4, releasedate: '2015-12-01', owned: true, completed: false, digital: true)
Game.create(name: 'Resident Evil - Revelations 2', console: ps4, releasedate: '2015-03-13', owned: true, completed: false, digital: true)
Game.create(name: 'Resident Evil HD', console: ps4, releasedate: '2015-01-20', owned: true, completed: false, digital: true)
Game.create(name: 'Mafia 3', console: ps4, releasedate: '2016-10-07', owned: false, completed: false, digital: false)
Game.create(name: 'Life is strange', console: ps4, releasedate: '2015-02-01', owned: true, completed: false, digital: true)
Game.create(name: 'Thief', console: ps4, releasedate: '2014-02-01', owned: true, completed: false, digital: false)
Game.create(name: 'Mortal Kombat X', console: ps4, releasedate: '2015-04-27', owned: true, completed: true, digital: false)
Game.create(name: 'Rocket League', console: ps4, releasedate: '2015-07-15', owned: true, completed: false, digital: true)
Game.create(name: 'Dishonored: Definitive Edition', console: ps4, releasedate: '2015-08-25', owned: true, completed: false, digital: true)
Game.create(name: 'Tony Hawks Pro Skater 5', console: ps4, releasedate: '2015-10-02', owned: false, completed: false, digital: false)
Game.create(name: 'Darksiders 2: Definitive Edition', console: ps4, releasedate: '2015-10-06', owned: true, completed: false, digital: true)
Game.create(name: 'Fallout 4', console: ps4, releasedate: '2015-11-10', owned: true, completed: false, digital: false)
Game.create(name: 'Unravel', console: ps4, releasedate: '2016-02-09', owned: true, completed: false, digital: true)
Game.create(name: 'This war of mine: The little ones', console: ps4, releasedate: '2016-01-29', owned: true, completed: false, digital: true)
Game.create(name: 'God of War', console: ps4, releasedate: '2016-12-26', owned: false, completed: false, digital: false)
Game.create(name: 'SOMA', console: ps4, releasedate: '2016-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'NBA2K16', console: ps4, releasedate: '2014-11-14', owned: true, completed: false, digital: true)
Game.create(name: 'Watch Dogs 2', console: ps4, releasedate: '2016-11-15', owned: true, completed: false, digital: false)
Game.create(name: 'Wolfenstein: The new order', console: ps4, releasedate: '2015-10-21', owned: true, completed: false, digital: true)
Game.create(name: 'Steep', console: ps4, releasedate: '2016-12-02', owned: true, completed: false, digital: false)
Game.create(name: 'Everybody\'s gone to the rapture', console: ps4, releasedate: '2016-04-01', owned: true, completed: false, digital: false)
Game.create(name: 'Destiny', console: ps4, releasedate: '2014-07-01', owned: true, completed: true, digital: false)
Game.create(name: 'Resident Evil VII (7) Biohazard', console: ps4, releasedate: '2017-01-24', owned: true, completed: false, digital: false)
Game.create(name: 'Read Dead Redemption 2', console: ps4, releasedate: '2018-04-01', owned: false, completed: false, digital: false)
Game.create(name: 'Journey', console: ps4, releasedate: '2015-03-01', owned: true, completed: false, digital: true)
Game.create(name: 'Lords of the fallen', console: ps4, releasedate: '2016-06-01', owned: true, completed: false, digital: true)
Game.create(name: 'Saint Rows: Gat out of hell', console: ps4, releasedate: '2015-06-01', owned: true, completed: false, digital: true)
Game.create(name: 'Mark McMorris Infinite Air', console: ps4, releasedate: '2016-10-25', owned: true, completed: true, digital: false)
Game.create(name: 'Detroit', console: ps4, releasedate: '2018-04-01', owned: false, completed: false, digital: false)
Game.create(name: 'Days Gone', console: ps4, releasedate: '2018-04-01', owned: false, completed: false, digital: false)
Game.create(name: 'Bound', console: ps4, releasedate: '2017-01-01', owned: true, completed: false, digital: true)
Game.create(name: 'Uncharted: The Lost Legacy', console: ps4, releasedate: '2017-08-23', owned: true, completed: false, digital: false)
Game.create(name: 'Dirt Rally (VR)', console: ps4, releasedate: '2015-12-07', owned: true, completed: false, digital: true)
Game.create(name: 'Hidden Agenda', console: ps4, releasedate: '2017-11-21', owned: true, completed: false, digital: false)
Game.create(name: 'Horizon Zero Dawn', console: ps4, releasedate: '2017-03-01', owned: true, completed: false, digital: true)
